instance badge controller hack: copy start_response()
This caused::

  AttributeError: 'BadgeController' object has no attribute 'start_response'

in certain circumstances where a redirect exception is thrown.

The badges forms/listings should be simplified. It's not sane.